import {initializeApp} from 'firebase/app';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'firebase/auth';
import {getFirestore,collection,doc,getDoc,onSnapshot,addDoc,setDoc,deleteDoc,query,orderBy,where,writeBatch} from 'firebase/firestore';
import {getStorage,ref,uploadBytes,getDownloadURL,deleteObject} from 'firebase/storage';
import * as XLSX from 'xlsx';
import {Filesystem,Directory,Encoding} from '@capacitor/filesystem';
import {Share} from '@capacitor/share';
import {Capacitor} from '@capacitor/core';
import {firebaseConfig,firebaseConfigured} from './firebase-config.js';

const $=id=>document.getElementById(id), e={};
'login lbox lem lpw lgo lerr cst who out rA rT nF nI vFin vInv sum pres presInfo presW barf ft tipo clase claseW cat desc cant uni monto fecha prov foto prev save msg cats xl mes bus tabs list isum inom icat icant iest iubi iobs iSave iMsg ixl ifc ibus iList bk rs bmsg vis big'.split(' ').forEach(id=>e[id]=$(id));
const FC=['Diezmos y ofrendas','Donaciones','Construcción','Materiales','Mano de obra','Servicios','Transporte','Alimentación','Ayuda social','Mantenimiento','Otros'];
const IC=['Mobiliario','Sonido','Instrumentos','Electrónica','Cocina','Limpieza','Construcción','Oficina','Otros'];
const IS=['Bueno','Regular','Malo','En reparación','De baja'];
let auth,db,storage,user,role,movs=[],inv=[],budget=0,unMov,unInv,photo=null;
const admin=()=>role==='admin',tech=()=>role==='tecnico';
const money=n=>'Bs '+Number(n||0).toLocaleString('es-BO',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const today=()=>new Date().toISOString().slice(0,10),month=()=>new Date().toISOString().slice(0,7);
function msg(n,t,b=false){if(n){n.textContent=t;n.style.color=b?'var(--red)':'var(--muted)'}}
function options(n,a){n.innerHTML=a.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('')}
function init(){
 options(e.tipo,['ingreso','egreso']);options(e.clase,['general','mayor']);options(e.cat,FC);options(e.icat,IC);options(e.ifc,['Todas',...IC]);options(e.iest,IS);
 e.fecha.value=today();e.mes.value=month();tabs();section('fin');e.login.style.display='flex';e.lbox.hidden=false;
}
function tabs(){e.tabs.innerHTML=['Todos','Ingresos','Egresos','Mayores'].map((x,i)=>'<button data-f="'+x+'" class="'+(i?'':'on')+'">'+x+'</button>').join('');e.tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{e.tabs.querySelectorAll('button').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderMov()})}
function section(x){let f=x==='fin';e.vFin.hidden=!f;e.vInv.hidden=f;e.nF.classList.toggle('on',f);e.nI.classList.toggle('on',!f)}
function roleUI(){e.rA.classList.toggle('on',admin());e.rT.classList.toggle('on',tech());e.rA.disabled=e.rT.disabled=true;e.presW.hidden=!admin();e.xl.hidden=!admin();e.ixl.hidden=!admin();e.bk.hidden=!admin();e.rs.disabled=!admin();if(tech()){e.tipo.value='egreso';e.tipo.disabled=true;e.clase.value='mayor';e.clase.disabled=true}else{e.tipo.disabled=false;e.clase.disabled=false}formUI()}
function formUI(){let ing=e.tipo.value==='ingreso';e.claseW.hidden=ing&&!tech();e.ft.textContent=ing?'Registrar ingreso':'Registrar egreso'}
async function getRole(uid){let s=await getDoc(doc(db,'usuarios',uid));if(!s.exists())throw Error('El usuario no tiene rol asignado.');let r=s.data().rol;if(!['admin','tecnico'].includes(r))throw Error('Rol inválido.');return r}
function visible(){return tech()?movs.filter(x=>x.t==='mayor'):movs}
function listeners(){
 if(unMov)unMov();if(unInv)unInv();
 let q=tech()?query(collection(db,'mov'),where('t','==','mayor')):query(collection(db,'mov'),orderBy('fecha','desc'));
 unMov=onSnapshot(q,s=>{movs=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.fecha||'').localeCompare(String(a.fecha||'')));renderAll()},x=>msg(e.cst,'Error movimientos: '+x.message,true));
 unInv=onSnapshot(query(collection(db,'inv'),orderBy('nombre')),s=>{inv=s.docs.map(d=>({id:d.id,...d.data()}));renderInv()},x=>msg(e.cst,'Error inventario: '+x.message,true));
 getDoc(doc(db,'app','config')).then(s=>{budget=s.exists()?Number(s.data().presupuesto||0):0;e.pres.value=budget||'';summary()}).catch(()=>{});
}
function summary(){let a=visible(),inc=a.filter(x=>x.tipo==='ingreso').reduce((s,x)=>s+Number(x.monto||0),0),out=a.filter(x=>x.tipo==='egreso').reduce((s,x)=>s+Number(x.monto||0),0),maj=a.filter(x=>x.tipo==='egreso'&&x.t==='mayor').reduce((s,x)=>s+Number(x.monto||0),0);e.sum.innerHTML='<div class="in"><small>Ingresos</small><b>'+money(inc)+'</b></div><div class="out"><small>Egresos</small><b>'+money(out)+'</b></div><div class="obra"><small>Gastos mayores</small><b>'+money(maj)+'</b></div><div><small>Saldo</small><b>'+money(inc-out)+'</b></div>';let p=budget?Math.min(100,maj/budget*100):0;e.barf.style.width=p+'%';e.presInfo.textContent=budget?'Ejecutado: '+money(maj)+' de '+money(budget)+' ('+p.toFixed(1)+'%).':'Presupuesto no definido.'}
function cats(){let m={};visible().filter(x=>x.tipo==='egreso').forEach(x=>m[x.cat]=(m[x.cat]||0)+Number(x.monto||0));let a=Object.entries(m).sort((x,y)=>y[1]-x[1]);e.cats.innerHTML=a.length?a.map(([k,v])=>'<p><span>'+esc(k)+'</span> <b>'+money(v)+'</b></p>').join(''):'<p class="empty">Sin egresos.</p>'}
function renderMov(){let f=e.tabs.querySelector('.on')?.dataset.f||'Todos',m=e.mes.value,q=(e.bus.value||'').toLowerCase(),a=visible().filter(x=>(!m||String(x.fecha||'').startsWith(m))&&(!q||JSON.stringify(x).toLowerCase().includes(q)));if(f==='Ingresos')a=a.filter(x=>x.tipo==='ingreso');if(f==='Egresos')a=a.filter(x=>x.tipo==='egreso');if(f==='Mayores')a=a.filter(x=>x.t==='mayor');e.list.innerHTML=a.length?a.map(x=>'<div class="item"><div><p><b>'+esc(x.desc||'Sin descripción')+'</b></p><p class="m">'+esc(x.fecha||'')+' · '+esc(x.cat||'')+(x.t?' · '+esc(x.t):'')+'</p>'+(x.fotoUrl?'<button class="ver" data-photo="'+esc(x.fotoUrl)+'">Ver foto</button>':'')+(admin()?'<button class="del" data-del="'+x.id+'" data-path="'+esc(x.fotoPath||'')+'">Eliminar</button>':'')+'</div><div class="amt '+(x.tipo==='ingreso'?'i':'e')+'">'+(x.tipo==='ingreso'?'+':'-')+' '+money(x.monto)+'</div></div>').join(''):'<p class="empty">No hay movimientos.</p>';e.list.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{e.big.src=b.dataset.photo;e.vis.style.display='flex'});e.list.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeMov(b.dataset.del,b.dataset.path))}
function renderInv(){let total=inv.reduce((s,x)=>s+Number(x.cantidad||0),0),bad=inv.filter(x=>['Malo','En reparación','De baja'].includes(x.estado)).reduce((s,x)=>s+Number(x.cantidad||0),0);e.isum.innerHTML='<div><small>Artículos</small><b>'+inv.length+'</b></div><div class="in"><small>Unidades</small><b>'+total+'</b></div><div class="out"><small>Con incidencia</small><b>'+bad+'</b></div><div class="obra"><small>Categorías</small><b>'+new Set(inv.map(x=>x.categoria)).size+'</b></div>';let fc=e.ifc.value||'Todas',q=(e.ibus.value||'').toLowerCase(),a=inv.filter(x=>(fc==='Todas'||x.categoria===fc)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));e.iList.innerHTML=a.length?a.map(x=>'<div class="item"><div><p><b>'+esc(x.nombre)+'</b></p><p class="m">'+esc(x.categoria)+' · '+esc(x.estado)+' · '+esc(x.ubicacion||'')+'</p>'+(admin()?'<button class="del" data-i="'+x.id+'">Eliminar</button>':'')+'</div><div class="amt">'+Number(x.cantidad||0)+'</div></div>').join(''):'<p class="empty">Sin artículos.</p>';e.iList.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>removeInv(b.dataset.i))}
function renderAll(){summary();cats();renderMov()}
async function saveMov(){msg(e.msg,'Guardando...');try{let tipo=tech()?'egreso':e.tipo.value,t=tipo==='egreso'?(tech()?'mayor':e.clase.value):'',monto=Number(e.monto.value);if(!e.desc.value.trim())throw Error('Ingrese una descripción.');if(!(monto>0))throw Error('El monto debe ser mayor a cero.');let fotoUrl='',fotoPath='';if(photo){if(photo.size>5*1024*1024||!photo.type.startsWith('image/'))throw Error('La foto debe ser imagen y menor a 5 MB.');fotoPath='facturas/'+user.uid+'/'+Date.now()+'-'+photo.name.replace(/[^a-zA-Z0-9._-]/g,'_');let rr=ref(storage,fotoPath);await uploadBytes(rr,photo,{contentType:photo.type});fotoUrl=await getDownloadURL(rr)}await addDoc(collection(db,'mov'),{tipo,t,cat:e.cat.value,desc:e.desc.value.trim(),cantidad:Number(e.cant.value||0),unidad:e.uni.value.trim(),monto,fecha:e.fecha.value,prov:e.prov.value.trim(),fotoUrl,fotoPath,uid:user.uid,creadoEn:Date.now()});e.desc.value=e.cant.value=e.uni.value=e.monto.value=e.prov.value='';e.foto.value='';photo=null;e.prev.style.display='none';msg(e.msg,'Movimiento guardado.')}catch(x){msg(e.msg,x.message,true)}}
async function saveInv(){try{let n=e.inom.value.trim(),c=Number(e.icant.value);if(!n||c<1)throw Error('Complete artículo y cantidad.');await addDoc(collection(db,'inv'),{nombre:n,categoria:e.icat.value,cantidad:c,estado:e.iest.value,ubicacion:e.iubi.value.trim(),obs:e.iobs.value.trim(),uid:user.uid,creadoEn:Date.now()});e.inom.value=e.icant.value=e.iubi.value=e.iobs.value='';msg(e.iMsg,'Artículo guardado.')}catch(x){msg(e.iMsg,x.message,true)}}
async function removeMov(id,p){if(admin()&&confirm('¿Eliminar movimiento?')){await deleteDoc(doc(db,'mov',id));if(p)try{await deleteObject(ref(storage,p))}catch{}}}
async function removeInv(id){if(admin()&&confirm('¿Eliminar artículo?'))await deleteDoc(doc(db,'inv',id))}
async function saveBudget(){if(admin()){budget=Number(e.pres.value||0);await setDoc(doc(db,'app','config'),{presupuesto:budget},{merge:true});summary()}}
function b64(b){let s='',a=new Uint8Array(b);for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(s)}
async function shareBinary(name,data,type){if(Capacitor.isNativePlatform()){let r=await Filesystem.writeFile({path:name,data:b64(data),directory:Directory.Cache});await Share.share({title:name,url:r.uri})}else{let u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}
async function excel(kind){if(!admin())return;let wb=XLSX.utils.book_new(),rows=kind==='mov'?visible().map(x=>({Fecha:x.fecha,Tipo:x.tipo,Clase:x.t,Categoría:x.cat,Descripción:x.desc,Cantidad:x.cantidad,Unidad:x.unidad,Monto:x.monto,Proveedor:x.prov})):inv.map(x=>({Artículo:x.nombre,Categoría:x.categoria,Cantidad:x.cantidad,Estado:x.estado,Ubicación:x.ubicacion,Observación:x.obs}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),kind==='mov'?'Movimientos':'Inventario');await shareBinary(kind+'-'+today()+'.xlsx',XLSX.write(wb,{bookType:'xlsx',type:'array'}),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}
async function backup(){if(!admin())return;let text=JSON.stringify({version:1,exportadoEn:new Date().toISOString(),presupuesto:budget,movimientos:movs,inventario:inv},null,2),name='embajada-backup-'+today()+'.json';if(Capacitor.isNativePlatform()){let r=await Filesystem.writeFile({path:name,data:text,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:name,url:r.uri})}else{let u=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click()}msg(e.bmsg,'Copia generada.')}
async function restore(file){if(!admin()||!file)return;try{let d=JSON.parse(await file.text());if(!Array.isArray(d.movimientos)||!Array.isArray(d.inventario))throw Error('Copia inválida.');if(!confirm('¿Restaurar la copia?'))return;let b=writeBatch(db);d.movimientos.forEach(x=>{let{id,...z}=x;b.set(doc(collection(db,'mov')),{...z,restauradoEn:Date.now()})});d.inventario.forEach(x=>{let{id,...z}=x;b.set(doc(collection(db,'inv')),{...z,restauradoEn:Date.now()})});if(Number.isFinite(Number(d.presupuesto)))b.set(doc(db,'app','config'),{presupuesto:Number(d.presupuesto)},{merge:true});await b.commit();msg(e.bmsg,'Copia restaurada.')}catch(x){msg(e.bmsg,x.message,true)}}
function wire(){e.lgo.onclick=async()=>{try{await signInWithEmailAndPassword(auth,e.lem.value.trim(),e.lpw.value)}catch{x=>x;msg(e.lerr,'No se pudo iniciar sesión.',true)}};e.out.onclick=()=>signOut(auth);e.nF.onclick=()=>section('fin');e.nI.onclick=()=>section('inv');e.tipo.onchange=formUI;e.save.onclick=saveMov;e.iSave.onclick=saveInv;e.mes.oninput=e.bus.oninput=renderMov;e.ifc.onchange=e.ibus.oninput=renderInv;e.pres.onchange=saveBudget;e.xl.onclick=()=>excel('mov');e.ixl.onclick=()=>excel('inv');e.bk.onclick=backup;e.rs.onchange=()=>restore(e.rs.files?.[0]);e.foto.onchange=()=>{photo=e.foto.files?.[0]||null;if(photo){e.prev.src=URL.createObjectURL(photo);e.prev.style.display='block'}else e.prev.style.display='none'};e.vis.onclick=()=>e.vis.style.display='none'}
async function boot(){init();if(!firebaseConfigured()){e.lgo.disabled=true;msg(e.lerr,'Firebase aún no está configurado.',true);msg(e.cst,'Firebase no configurado.',true);return}initializeApp(firebaseConfig);auth=getAuth();db=getFirestore();storage=getStorage();wire();onAuthStateChanged(auth,async u=>{if(!u){user=role=null;movs=[];inv=[];e.login.style.display='flex';e.lbox.hidden=false;msg(e.cst,'Sesión cerrada.');return}try{user=u;role=await getRole(u.uid);roleUI();e.login.style.display='none';msg(e.who,(u.email||'')+' · '+(admin()?'Administrador':'Técnico'));msg(e.cst,'Conectado con Firebase.');listeners()}catch(x){msg(e.lerr,x.message,true);await signOut(auth)}})}
boot();